[drift_detection]
report_table = "drift_report"

[[drift_detection.tables]]
current_table = "../data/validated_pays.csv"

columns = [{ name = "total", type = "numeric", method = "psi_calculator" }]

[[drift_detection.tables]]
current_table = "../data/validated_prints.csv"

columns = [{ name = "position", type = "numeric", method = "kl_divergence" }]

[[drift_detection.tables]]
current_table = "../data/validated_taps.csv"

columns = [{ name = "position", type = "numeric", method = "z_test" }]


[loggers_selection]
# This is a list of loggers that will be enabled. If not set, all loggers will be enabled.

loggers = ["console", "file"] # console "file"]


[logging]
level = "DEBUG" # DEBUG, INFO, WARN, ERROR, CRITICAL

[logging.formats]
simple = "<level>{message}</level>"
detailed = "<green>{time:YYYY-MM-DD at HH:mm:ss}</green> | <level>{level: <8}</level> | <cyan>{name}</cyan>:<cyan>{function}</cyan>:<cyan>{line}</cyan> - <level>{message}</level>"

[logging.console]
format = "detailed"
level = "DEBUG"

[logging.file]
path = "app.log"
rotation = "1 week"
retention = "1 month"
format = "detailed"
level = "DEBUG"
